### ISSUE TITLE
java.io.IOException: No subject alternative names present

### ISSUE THREAD

**Issue by beta-ziliani** [xpierrohk/DigitalPaperApp#7]
I'm running the command `dpt ping -addr=192.168.XX.XX` (or any other command) and it fails with the given exception. Oddly enough, I manage to register it using `dpt register -addr=...`. No idea what can cause the problem. It is using the latest firmware.

UPDATE: I get the same exception if I remove -addr=

**Comment by xpierrohk** [comment]
Hum, I think this is because it may try to do https on "dpt.local" and you have some issue, for some reason... I dont have mine on me right now, maybe this weekend, worst case Monday.

A few things you can do to help me:

- What linux version do you use exactly ? I'll try to get it on a VM.
- Can you try to register without the -addr ?
- Can you give me the content of your ~/.dpt , I think I remember I store some cert-related stuff there, we can see what the alternative name field is in there

Have you tried the other app in python btw ? It is by default insecure, while mine tried to be fancy and therefore will have these weird issue.

**Comment by beta-ziliani** [comment]
>     * What linux version do you use exactly ? I'll try to get it on a VM.
Ubuntu 18.04 on an old kernel (drivers issues): 4.15.0-1096-oem.
 
>     * Can you try to register without the -addr ?
Nope:
`java.net.UnknownHostException: digitalpaper.local: Name or service not known`

>     * Can you give me the content of your ~/home/.dpt , I think I remember I store some cert-related stuff there
 * cert.pem (---- BEGIN CERTIFICATE --- .... ----- END CERTIFICATE ------
 * client_id.dat (some hex numbers)
 * id_rsa (what you expect)
 * last_connection.ip (the last ip used)

Let me know if you need details about any of these fails.

**Comment by beta-ziliani** [comment]
The Python one works, but it lacks the whiteboard option :-)

EDIT: But the discovery option doesn't work either. I have to provide the address manually.

**Comment by beta-ziliani** [comment]
UPDATE: it started working all of the sudden, also with automatic discovering of the device and all. No idea what changed... I will try to find out.
